#!/bin/sh

set -a
if [ -f ../.env ]; then
  . ../.env
fi
set +a

REACT_APP_MSAL_CLIENT_ID="${REACT_APP_MSAL_CLIENT_ID:-${MSAL_CLIENT_ID:-}}" \
REACT_APP_MSAL_TENANT_ID="${REACT_APP_MSAL_TENANT_ID:-${AZURE_TENANT_ID:-}}" \
REACT_APP_REDIRECT_URI="${REACT_APP_REDIRECT_URI:-${FRONTEND_REDIRECT_URI:-}}" \
REACT_APP_BACKEND_URL="${REACT_APP_BACKEND_URL:-${BACKEND_URL:-}}" \
REACT_APP_AGENT_NAME="${REACT_APP_AGENT_NAME:-${AGENT_NAME:-FoundryAtlassianAgent}}" \
PORT="${PORT:-3500}" \
react-scripts start
